spring:

# JPA
  jpa:
    generate-ddl: false
    hibernate:
      ddl-auto: validate
    open-in-view: false

# RDB
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://${SPRING_DATASOURCE_HOSTNAME}:${SPRING_DATASOURCE_PORT}/${SPRING_DATASOURCE_DATABASE_NAME}?serverTimezone=UTC&useUnicode=true&characterEncoding=UTF-8
    username: ${SPRING_DATASOURCE_USERNAME}
    hikari:
      max-lifetime: 720000

# Redis
  data:
    redis:
      host: ${SPRING_REDIS_HOST}
      port: ${SPRING_REDIS_PORT}

# Sentry
sentry:
  dsn: ${SENTRY_DSN}
  environment: dev
  send-default-pii: false
  traces-sample-rate: 1.0
  exception-resolver-order: -2147483647
  max-request-body-size: always

# Actuator
management:
  server:
    port: 8080
  endpoints:
    web:
      exposure:
        include: "*"
